server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: 06494784
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-module
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            spl: trace