server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: Az456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order-module
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs